// 由 database/schema.sql 自动拆分生成（触发器块已合并）——用于测试环境初始化表结构
export const schemaStatements: string[] = [
  "CREATE TABLE IF NOT EXISTS users (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    username TEXT UNIQUE NOT NULL,\n    email TEXT UNIQUE NOT NULL,\n    password_hash TEXT NOT NULL,\n    display_name TEXT NOT NULL,\n    avatar_url TEXT,\n    bio TEXT,\n    role TEXT DEFAULT 'admin' CHECK (role IN ('admin', 'editor')),\n    is_active BOOLEAN DEFAULT 1,\n    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP\n)",
  "CREATE TABLE IF NOT EXISTS categories (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    name TEXT UNIQUE NOT NULL,\n    slug TEXT UNIQUE NOT NULL,\n    description TEXT,\n    color TEXT DEFAULT '#3B82F6',\n    sort_order INTEGER DEFAULT 0,\n    is_active BOOLEAN DEFAULT 1,\n    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP\n)",
  "CREATE TABLE IF NOT EXISTS tags (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    name TEXT UNIQUE NOT NULL,\n    slug TEXT UNIQUE NOT NULL,\n    description TEXT,\n    color TEXT DEFAULT '#10B981',\n    usage_count INTEGER DEFAULT 0,\n    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP\n)",
  "CREATE TABLE IF NOT EXISTS posts (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    title TEXT NOT NULL,\n    slug TEXT UNIQUE NOT NULL,\n    excerpt TEXT,\n    content TEXT NOT NULL,\n    featured_image TEXT,\n    category_id INTEGER,\n    author_id INTEGER NOT NULL,\n    status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),\n    is_featured BOOLEAN DEFAULT 0,\n    view_count INTEGER DEFAULT 0,\n    comment_count INTEGER DEFAULT 0,\n    published_at DATETIME,\n    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL,\n    FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE\n)",
  "CREATE TABLE IF NOT EXISTS post_tags (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    post_id INTEGER NOT NULL,\n    tag_id INTEGER NOT NULL,\n    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,\n    FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE,\n    UNIQUE(post_id, tag_id)\n)",
  "CREATE TABLE IF NOT EXISTS comments (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    post_id INTEGER NOT NULL,\n    parent_id INTEGER,\n    author_name TEXT NOT NULL,\n    author_email TEXT NOT NULL,\n    author_website TEXT,\n    author_ip TEXT,\n    content TEXT NOT NULL,\n    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'spam')),\n    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,\n    FOREIGN KEY (parent_id) REFERENCES comments(id) ON DELETE CASCADE\n)",
  "CREATE TABLE IF NOT EXISTS settings (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    key TEXT UNIQUE NOT NULL,\n    value TEXT,\n    type TEXT DEFAULT 'string' CHECK (type IN ('string', 'number', 'boolean', 'json')),\n    description TEXT,\n    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP\n)",
  "CREATE TABLE IF NOT EXISTS pages (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    title TEXT NOT NULL,\n    slug TEXT UNIQUE NOT NULL,\n    content TEXT NOT NULL,\n    meta_description TEXT,\n    is_published BOOLEAN DEFAULT 1,\n    sort_order INTEGER DEFAULT 0,\n    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP\n)",
  "CREATE INDEX IF NOT EXISTS idx_posts_status ON posts(status)",
  "CREATE INDEX IF NOT EXISTS idx_posts_published_at ON posts(published_at DESC)",
  "CREATE INDEX IF NOT EXISTS idx_posts_category ON posts(category_id)",
  "CREATE INDEX IF NOT EXISTS idx_posts_author ON posts(author_id)",
  "CREATE INDEX IF NOT EXISTS idx_posts_slug ON posts(slug)",
  "CREATE INDEX IF NOT EXISTS idx_comments_post ON comments(post_id)",
  "CREATE INDEX IF NOT EXISTS idx_comments_status ON comments(status)",
  "CREATE INDEX IF NOT EXISTS idx_post_tags_post ON post_tags(post_id)",
  "CREATE INDEX IF NOT EXISTS idx_post_tags_tag ON post_tags(tag_id)",
  "CREATE INDEX IF NOT EXISTS idx_categories_slug ON categories(slug)",
  "CREATE INDEX IF NOT EXISTS idx_tags_slug ON tags(slug)",
  "CREATE INDEX IF NOT EXISTS idx_settings_key ON settings(key)",
  "CREATE INDEX IF NOT EXISTS idx_pages_slug ON pages(slug)",
  "CREATE TRIGGER IF NOT EXISTS update_users_updated_at \n    AFTER UPDATE ON users\n    BEGIN\n        UPDATE users SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;\n    END",
  "CREATE TRIGGER IF NOT EXISTS update_categories_updated_at \n    AFTER UPDATE ON categories\n    BEGIN\n        UPDATE categories SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;\n    END",
  "CREATE TRIGGER IF NOT EXISTS update_tags_updated_at \n    AFTER UPDATE ON tags\n    BEGIN\n        UPDATE tags SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;\n    END",
  "CREATE TRIGGER IF NOT EXISTS update_posts_updated_at \n    AFTER UPDATE ON posts\n    BEGIN\n        UPDATE posts SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;\n    END",
  "CREATE TRIGGER IF NOT EXISTS update_comments_updated_at \n    AFTER UPDATE ON comments\n    BEGIN\n        UPDATE comments SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;\n    END",
  "CREATE TRIGGER IF NOT EXISTS update_settings_updated_at \n    AFTER UPDATE ON settings\n    BEGIN\n        UPDATE settings SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;\n    END",
  "CREATE TRIGGER IF NOT EXISTS update_pages_updated_at \n    AFTER UPDATE ON pages\n    BEGIN\n        UPDATE pages SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;\n    END",
  "CREATE TRIGGER IF NOT EXISTS increment_tag_usage \n    AFTER INSERT ON post_tags\n    BEGIN\n        UPDATE tags SET usage_count = usage_count + 1 WHERE id = NEW.tag_id;\n    END",
  "CREATE TRIGGER IF NOT EXISTS decrement_tag_usage \n    AFTER DELETE ON post_tags\n    BEGIN\n        UPDATE tags SET usage_count = usage_count - 1 WHERE id = OLD.tag_id;\n    END",
  "CREATE TRIGGER IF NOT EXISTS increment_comment_count \n    AFTER INSERT ON comments\n    BEGIN\n        UPDATE posts SET comment_count = comment_count + 1 WHERE id = NEW.post_id;\n    END",
  "CREATE TRIGGER IF NOT EXISTS decrement_comment_count \n    AFTER DELETE ON comments\n    BEGIN\n        UPDATE posts SET comment_count = comment_count - 1 WHERE id = OLD.post_id;\n    END",
];
